word_id: ok_goddess
display_name: Ok Goddess
trained_languages:
- en
piper:
  batch_size: 50
  length_scales:
  - 0.75
  - 1.0
  - 1.25
  model: en_US-libritts_r-medium.pt
  model_url: https://github.com/rhasspy/piper-sample-generator/releases/download/v2.0.0/en_US-libritts_r-medium.pt
  noise_scale_ws:
  - 0.98
  noise_scales:
  - 0.98
espeak:
  voices:
  - en
  - en-us
  - en-gb
samples:
  negative_train: 30000
  negative_val: 2000
  positive_train: 20000
  positive_val: 2000
augmentation:
  batch_size: 16
  rounds: 3
oww:
  layer_size: 32
  max_negative_weight: 1500
  model_type: dnn
  steps: 50000
  target_fp_per_hour: 0.2
custom_negative_phrases:
- a goddess
- awk goddess
- goddess is
- oak goddess
- oh goddess
- ok god is
- ok god us
- ok god yes
- ok goddess
- ok godless
- ok goodness
- okay goddess
- the goddess
- uh goddess
notes: 'Future batch. Created 2026-03-25.

  '
