#!/usr/bin/env python3
"""
Train microWakeWord model for ESPHome HA Voice PE firmware.

Uses the microWakeWord framework (kahrendt/microWakeWord) which produces
streaming TFLite models small enough for ESP32-S3 on-chip inference.
GPU accelerated where possible (feature extraction, training).

Usage: python 04_train_mww.py <word_id>
"""
import argparse
import logging
import os
import sys
from pathlib import Path

import yaml
import torch
import numpy as np

logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s [%(levelname)s] %(message)s",
)
log = logging.getLogger(__name__)

SCRIPT_DIR = Path(__file__).resolve().parent
REPO_DIR = SCRIPT_DIR.parent
MWW_DIR = Path(os.environ.get("MWW_PATH", str(REPO_DIR / "microWakeWord")))


def detect_device():
    if torch.cuda.is_available():
        name = torch.cuda.get_device_name(0)
        log.info("GPU: %s — using CUDA for mWW training", name)
        return "cuda"
    log.warning("No CUDA GPU — mWW training on CPU")
    return "cpu"


def load_config(word_id: str) -> dict:
    cfg_path = REPO_DIR / "words" / word_id / "config.yaml"
    with open(cfg_path) as f:
        return yaml.safe_load(f)


def ensure_mww_installed():
    """Verify microWakeWord is available."""
    try:
        import microwakeword
        log.info("microWakeWord version: %s", getattr(microwakeword, "__version__", "unknown"))
        return True
    except ImportError:
        log.error(
            "microWakeWord not installed. Run:\n"
            "  pip install microwakeword\n"
            "or build the Docker image:\n"
            "  docker build -t mww-train -f docker/Dockerfile.mww ."
        )
        return False


def train_mww(cfg: dict, device: str):
    """Train a microWakeWord model."""
    word_id = cfg["word_id"]
    target_phrase = cfg["display_name"].lower()
    artifact_dir = REPO_DIR / "artifacts" / word_id
    mww_out = artifact_dir / "mww"
    mww_out.mkdir(parents=True, exist_ok=True)

    # microWakeWord uses its own training config format
    # Point it at the same audio samples generated by step 01
    pos_train_dir = artifact_dir / "positive_train"
    neg_train_dir = artifact_dir / "negative_train"
    pos_val_dir = artifact_dir / "positive_val"
    neg_val_dir = artifact_dir / "negative_val"

    for d in [pos_train_dir, pos_val_dir]:
        if not d.exists() or not list(d.glob("*.wav")):
            log.error("No samples found in %s — run 01_generate_samples.py first", d)
            sys.exit(1)

    try:
        from microwakeword.train import train as mww_train_func
    except ImportError:
        log.error("Cannot import microwakeword.train — check installation")
        sys.exit(1)

    # Build microWakeWord config
    mww_config = {
        "wake_word": target_phrase,
        "model_name": word_id,
        "positive_train_dir": str(pos_train_dir),
        "positive_val_dir": str(pos_val_dir),
        "negative_train_dir": str(neg_train_dir),
        "negative_val_dir": str(neg_val_dir),
        "output_dir": str(mww_out),
        "epochs": 100,
        "batch_size": 64,
        "learning_rate": 0.001,
    }

    config_path = mww_out / "train_config.yaml"
    with open(config_path, "w") as f:
        yaml.dump(mww_config, f, default_flow_style=False)

    log.info("microWakeWord training config: %s", config_path)
    log.info("Starting mWW training (device=%s)...", device)

    # microWakeWord uses TensorFlow; set GPU memory growth
    if device == "cuda":
        try:
            import tensorflow as tf
            gpus = tf.config.list_physical_devices("GPU")
            for gpu in gpus:
                tf.config.experimental.set_memory_growth(gpu, True)
            log.info("TensorFlow GPU devices: %s", gpus)
        except RuntimeError as e:
            log.warning("TF GPU setup: %s", e)

    mww_train_func(config_path=str(config_path))

    # Check output
    tflite_files = list(mww_out.glob("*.tflite"))
    if tflite_files:
        for f in tflite_files:
            log.info("mWW model: %s (%.1f KB)", f.name, f.stat().st_size / 1024)
    else:
        log.warning("No TFLite files produced — check training logs")


def main():
    parser = argparse.ArgumentParser(description="Train microWakeWord model")
    parser.add_argument("word_id", help="Wake word identifier")
    args = parser.parse_args()

    cfg = load_config(args.word_id)
    device = detect_device()

    if not ensure_mww_installed():
        sys.exit(1)

    train_mww(cfg, device)
    log.info("mWW training complete for '%s'", cfg["display_name"])


if __name__ == "__main__":
    main()
