trained_languages:
- en
piper:
  batch_size: 50
  length_scales:
  - 0.75
  - 1.0
  - 1.25
  model: en_US-libritts_r-medium.pt
  model_url: https://github.com/rhasspy/piper-sample-generator/releases/download/v2.0.0/en_US-libritts_r-medium.pt
  noise_scale_ws:
  - 0.98
  noise_scales:
  - 0.98
espeak:
  voices:
  - en
  - en-us
  - en-gb
samples:
  positive_train: 20000
  positive_val: 2000
  negative_train: 40000
  negative_val: 2000
augmentation:
  batch_size: 16
  rounds: 3
oww:
  model_type: dnn
  layer_size: 64
  steps: 150000
  max_negative_weight: 50000
  target_fp_per_hour: 0.2
word_id: my_lord
display_name: My Lord
custom_negative_phrases:
- my word
- my lord is
- my board
- my cord
- my ford
- my sword
- my horde
- my landlord
- by lord
- my lore
- my law
- my floor
- my large
- my lost
- my lot
- my laud
notes: New word. Created 2026-06-02.
